### ISSUE TITLE
How to get to Builder from Reader?

### ISSUE THREAD

**Issue by polachok** [capnproto/capnpc-rust#45]
I receive messages from network, get a reader using read_message.
Now I'd like to inspect some fields and send it further without copying.
Is it possible?

**Comment by dwrensha** [comment]
Are you modifying the message, or are you just forwarding it as-is?

If you're modifying the message, you'll need to copy it with `message::Builder::set_root()`. Directly pushing the message's bytes into a `message::Builder` would be unsafe, because `message::Builder` assumes that its data is a valid message, and therefore it performs fewer validations (bounds checks, etc.) than `message::Reader` does when traversing a message. Copying the data into the `Builder` with `set_root()` will perform all the necessary validations to make the data safe to use in a `Builder`.

If you're not modifying the message, then we can probably figure out a way for you to avoid the copy. I think the easiest thing would be for us to add a variant of [`serialize::write_message()`](https://github.com/capnproto/capnproto-rust/blob/ccbe348e861596b3d9a48d87d3b6ef6b4eafb600/src/serialize.rs#L197) that takes a `message::Reader` rather than a `message::Builder`. To achieve that, I imagine that we would redefine [`write_segment_table()`](https://github.com/capnproto/capnproto-rust/blob/ccbe348e861596b3d9a48d87d3b6ef6b4eafb600/src/serialize.rs#L207) and [`write_segments()`](https://github.com/capnproto/capnproto-rust/blob/ccbe348e861596b3d9a48d87d3b6ef6b4eafb600/src/serialize.rs#L243) to take a `ReaderSegments` rather than a `&[&[Word]]`.

**Comment by polachok** [comment]
I don't modify it, just pass along as is.

**Comment by dwrensha** [comment]
Fixed by https://github.com/capnproto/capnproto-rust/pull/86.

**Comment by MoreTore** [comment]
@dwrensha how would you copy the data into the Builder with set_root() for modification? 

i have opened this discussion: https://github.com/capnproto/capnproto-rust/discussions/509
